# NumPy

- NumPy(Numerical Python)는 선형대수 기반 수치 계산 및 데이터 분석을 위한 강력한 파이썬 라이브러리입니다. 주로 다차원 배열 처리와 관련된 기능을 제공하며, 데이터 과학, 머신러닝, 시뮬레이션 및 기타 과학 계산 분야에서 널리 사용됩니다.

- C로 구현되어 있어 일반적인 파이썬 리스트보다 빠르고 메모리 효율적입니다.

- NumPy는 다른 라이브러리(예: Pandas, TensorFlow, PyTorch)에서도 핵심 기반으로 사용되며, 파이썬 생태계에서 매우 중요한 역할을 합니다.

- Scikit-learn : numpy배열을 입력으로 받음. 또한 연산도 numpy함수를 쓰는 경우가 많음.
- 머신러닝에서 '전처리는 필수' pandas
- 머신러닝 패키지와 전처리 패키지 간 연계가 자유롭다.

## 설치 및 기본

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np
# 배열 생성
a = np.array([1,2,3,4])
print(f'배열{a}, 타입{type(a)}')
# 배열 연산
# list : 1234, 1234 두번 반복
listA = [1,2,3,4]
listB = listA *2
listB 
# array : 배열하나하나에 적용됨
b = a * 2
b

배열[1 2 3 4], 타입<class 'numpy.ndarray'>


array([2, 4, 6, 8])

## 파이썬의 리스트를 넘파이 배열로 바꾸기

In [4]:
A = [[1,2],[3,4]]
print(type(A))
A_numpy = np.array(A)
print(type(A_numpy))
A_numpy 

<class 'list'>
<class 'numpy.ndarray'>


array([[1, 2],
       [3, 4]])

## 넘파이 배열을 리스트로 바꾸기

In [6]:
list_a = A_numpy.tolist()
print(list_a, type(list_a))

[[1, 2], [3, 4]] <class 'list'>


## 전치행렬

In [9]:
co = np.array([[1,2,3],[4,5,6]])
print(co)
print(co.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## 배열 확인

In [11]:
# 데이터타입 확인
co.dtype # array 배열에서는 dtype이 섞이면 안됨.

dtype('int64')

In [12]:
# 차원, 크기
print(co.ndim) # 차원
print(co.shape) # 크기 # 행2개 열3개

2
(2, 3)


## range로 배열 생성

In [14]:
np.arange(10) # 테스트 데이터셋(차원과 크기가 같은) 만들때 유용하게 사용

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 인덱싱

In [24]:
array1 = np.arange(1,10)
array1[:3]

array([1, 2, 3])

In [14]:
array2 = np.arange(1,10) # 1차원 배열
# shpae(행,열)a=
array2 = array2.reshape(3,3) # 2차원 배열


In [29]:
print(array2)
print(array2[:2 , :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [110]:
# 3 * 4 2차원 배열
# 0~3 사이의 임의의 실수(단 소숫점 아래 한자리)
# 넘파이 배열

import random # 랜덤 기능패키지를 불러오기 함
print(random.random()+0)
print(random.random()+1)
print(random.random()+2)

print(random.random()+i)

0.4755795996019664
1.1570519817878295
2.7521230086765778


NameError: name 'i' is not defined

In [ ]:
# 3 * 4  2차원배열
# 0~3 사이의 임의의 실수(단, 소숫점 아래 한자리)
# 넘파이 배열
array3 = np.random.rand(3, 4)

# 모든 데이터가 소숫점 아래 한자리
array3 = np.round(array3, 1)
print(array3)

In [7]:
list = []
import numpy as np

In [34]:
random_float = random.uniform(0, 3)
random_float

0.5057812751910009

In [36]:
import random
for i in range(0,12):
    random_float = random.uniform(0, 3)
    list.append(random_float)
len(list)


170

## 불린인덱싱
넘파이 배열 인덱싱에 조건을 붙이면 조건에 맞는 불리언배열이 만들어진다.
즉, 불리언배열을 가지고 값을 찾게 되는데 조건문
if/else를 사용한 방법 보다 훨씬 효율적이다.

In [21]:
array4 = np.arange(1, 10)
array4[array4 > 5]

array([6, 7, 8, 9])

## 정렬



*   np.sort(arraytest) 정렬된 배열을 반환
*   arraytest.sort() 원본정렬
*   np.sort(arraytest)[::-1] 내림차순
*   np.sort(arraytest, axis=0)  2차원일 경우 (열을 기준으로 정렬)
*   np.argsort() 정렬한 뒤, 정렬 전 인덱스를 반환

In [22]:
org_array = np.array([3, 1, 9, 5])
print('원본',org_array)

sorted_array = np.sort(org_array)
print('정렬',sorted_array)

reversed_array = np.sort(org_array)[::-1]
print('내림차순',reversed_array)

org_index = np.argsort(org_array)
print('정렬 전 인덱스',org_index)

원본 [3 1 9 5]
정렬 [1 3 5 9]
내림차순 [9 5 3 1]
정렬 전 인덱스 [1 0 3 2]


### 중복제거

In [35]:
dup_array = np.array([1, 1, 2, 2, 2, 3, 3, 4])
np.unique(dup_array)

array([1, 2, 3, 4])